movieapp/urls.py
from django.urls import path
from movieapp import views
app_name='movieapp'
urlpatterns = [
    path('',views.allMoviedetails,name='allMoviedetails'),
    path('<slug:c_slug>/',views.allMoviedetails,name='movie_details_by_category'),
    path('<slug:c_slug>/<slug:movie_slug>/',views.detailedOfMovie,name='detailedOfMovie'),

]

movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('movieapp.urls')),
    path('credential/',include('userapp.urls')),
    path('search/',include('searchapp.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

searchapp/urls.py
from django.urls import path
from . import views

app_name='searchapp'

urlpatterns=[
    path('',views.searchResult,name='searchResult'),
]

userapp/urls.py
from django.urls import path
from userapp import views
app_name='userapp'
urlpatterns = [
    path('register/',views.Register,name='register'),
    path('login/',views.Login,name='login'),
    path('logout/',views.Logout,name='logout'),
    path('addmovies/',views.AddMovies,name='addmovies'),
    path('update/<int:id>',views.Update,name='update'),
    path('delete/<int:id>/',views.Delete,name='delete'),
    path('updatedetails/<int:pk>/',views.ToDoUpdateView.as_view(),name='updatedetails'),
]

templates/addmovies.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Movie</title>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/ba5a227daf.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
   <div class="container">
        <div class="row justify-content-center" style="padding-top: 35px;">
            <div class="col-sm-8"></div>
            <div class="col-sm-4">
                <h1 style="text-align: center;">Add Movie</h1>
                <form method="post" action="" enctype="multipart/form-data" style="padding: 15px;" >
                    {% csrf_token %}
                    <input type="text" class="form-control" name="title" placeholder="Enter Movie Title "> <br>
                    <input type="text" class="form-control" name="slug" placeholder="Enter slug without space/*etc "> <br>
                    <input type="text" class="form-control" name="description" placeholder="Enter Movie Description "><br>
                    <input type="date" class="form-control" name="release_date" placeholder="Released Date (YYYY-MM-DD) "><br>
                    <input type="file" class="form-control" name="poster" ><br>
                    <input type="text"class="form-control"  name="actors" placeholder="Enter Cast Details "><br>
                    <input type="text" class="form-control" name="trailer_Link" placeholder="Add Trailer Link "><br>
                    <div class="form-group"><br>
                        <label for="dropdown">Category:</label>
                        <select class="form-control" id="dropdown" name="category">
                            <option value="Malayalam">Malayalam</option>
                            <option value="Comedy">Comedy</option>
                            <option value="Option">Option</option>
                            <option value="Tamil">Tamil</option>
                            <option value="Dramamovie">Dramamovie</option>
                            <option value="Horror">Horror</option>
                            <option value="Hindi">Hindi</option>
                       </select>
                    </div>
                    <input href type="submit">
                </form>
              {% for msg in messages %}
                {{msg}}
              {% endfor %}
            </div>
        </div>
   </div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <link rel="stylesheet" href="{% static 'static/css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/ba5a227daf.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="bg_default">
<div class="container-fluid">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html'%}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/ba5a227daf.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</head>
<body>
<form  method="post">
    {% csrf_token %}
    <h3>Your are Going to delete this Movie</h3>
    <a type="button"  class="btn btn-primary" href="{% url 'movieapp:allMoviedetails' %}">
        Go to Home
    </a>
    <button type="button"  class="btn btn-primary" data-toggle="modal" data-target="#delete">
        Proceed
    </button>
    <!-- Modal -->
    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" style="color: rgb(44, 44, 255);" id="exampleModalLongTitle"> Movie : {{details.title}}</h5>

                </div>
                <form  method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <p style="color: rgb(44, 44, 255);">Are your Sure you want to delete?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</form>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
MovieFlex
{% endblock %}
{% block title %}{{moviedts.title}}{% endblock %}
{% block content %}

<div class="container">
    <br>
    <div class="row">
        <div class ="col-12 col-sm-12 col-md-12 col-lg-6 text-center ">
            <div class="min-width:18rem">
                <img width="650px" height="400px" src="{{details.poster.url}}" alt="{{details.title}}">
            </div>
        </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6" style="padding-left: 30px;">
                <h1 class="my_prod_title">{{details.title}}</h1>
                <p style="font-size:22px;">Category: {{details.category}}</p>
                <p style="font-size:22px;">Released Date: {{details.release_date}}</p>
                <p class="text-justify my_prod_class">{{details.description}}</p>
                <p class="text-justify my_prod_class">Cast: {{details.actors}}</p>
                <p class="text-justify my_prod_class">Trailer: <a href="{{details.trailer_Link}}">{{details.trailer_Link}}</a></p>
                <a class="btn btn-warning" href="{% url 'userapp:updatedetails' details.id %}"><strong style="color: white;">Update</strong></a>
                <a class="btn btn-warning" href="{% url 'userapp:delete' details.id %}"><strong style="color: white;">Delete</strong></a>



            </div>
    </div>
</div>

<div class="container">
    <br>
    <div class="row">
        <div class ="col-12 col-sm-12 col-md-12 col-lg-6 text-center ">
            {% if user.is_authenticated %}
            <form method="post" style="padding: 15px;" action="" >
                {% csrf_token %}

                <div class="row ">
                    <input style="  color: white; width: 400px; height: 45px;" type="text" class="form-control plcdgn" name="comment" placeholder="Write Your Comments...">&nbsp; &nbsp;

                    <input class="btn " style="width: 100px; height: 45px; background-color: rgb(55, 152, 238);color: black;" type="submit">
                </div>
            </form>
            {% endif %}
        </div>
        <div class ="col-12 col-sm-12 col-md-12 col-lg-6 text-center ">
            <div>
                <br><h4 style="text-align: left;">Comments</h4>
                <ul>
                    <br>
                    {% for comment in comments %}
                        <div class="row">
                            <h6 style="color: black; text-align: justify;"> --> {{ comment.message }} </h6> <br>
                            <h7 style="color: black; text-align: left;">Comment by: {{ comment.user }} &nbsp; on&nbsp; &nbsp;{{ comment.date }}</h7>
                        </div>
                        <hr style="color: rgb(31, 79, 255);">
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>
</div>
{% endblock %}

templates/footer.html
{% load static %}
<footer class="bg-body-tertiary text-center text-lg-start">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <form action="">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-auto mb-4 mb-md-0">
          <p class="pt-2">
            <strong>Sign up for our movie</strong>
          </p>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-5 col-12 mb-4 mb-md-0">
          <!-- Email input -->
          <div data-mdb-input-init class="form-outline mb-4">
            <input type="email" id="form5Example22" class="form-control" />
            <label class="form-label" for="form5Example22">Email address</label>
          </div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-auto mb-4 mb-md-0">
          <!-- Submit button -->
          <button data-mdb-ripple-init type="button" class="btn btn-primary mb-4">
            Subscribe
          </button>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </form>
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: grey;">
    © 2024 Copyright:
    <a class="text-body" href="https://movieflex.com/">MovieFlex.com</a>
  </div>
  <!-- Copyright -->
</footer>

templates/header.html
{% load static %}
<div class="container-fluid" style="padding-top: 20px;background-color:black;">
<div class="row">
    <header>
        <div class="col-sm-8">
            <a style="text-decoration: none;text-align: left;" href="{% url 'movieapp:allMoviedetails' %}"> <h1 style="width: 301px;height: 55px; text-align: center;color: white;font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;"><strong style=" text-align: center;color: #2272FF;font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;font-size:60px">MovieFlex</strong></h1></a>
        </div>
        <div class="col-sm-4">
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="#" ><p style="width: 200px;height: 30px;color: yellow;text-align: right;font-size: 24px;" > <i>Hello, {{user.username}}</i></p></a>
            {% endif %}
        </div>

    </header>
</div>
</div>
<header>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Movie Flex
the latest movie.
{% endblock %}
{% block title %}MovieFlex{% endblock %}
{% block content %}
<br>
{% if c_slug is None  %}
    {% for cat in links %}
        <div><h3 style="margin-left: 5px;">{{cat.name}}</h3></div>
        <div class="container-fluid" style="overflow:auto;background-color: black;">
            <div class="scrolling-wrapper row flex-row flex-nowrap gx-2 mt-4 pb-4 pt-2 ">
                {% for movie in moviedetails.object_list %}
                    {% if movie.category.name == cat.name %}
                        <div class="card card-block col-4 col-9 col-sm-12 col-md-4  col-lg-4 mr-2 border-0"  style="width: 550px; background-color: black;">
                            <a href="{{movie.get_url}}"><img width="10px"  height="500px" src="{{movie.poster.url}}" class="card-img-top" alt="{{movie.title}}"></a>
                            <a href="{{movie.get_url}}"><div class="card-img-overlay">
                                <h5 class="card-title" style="color: white;font-size:200%">{{movie.title}}</h5>
                                <p class=""></p>
                            </div></a>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <br>
    {% endfor %}

{% else %}

<div><h3 style="margin-left: 5px;">{{c_slug}}</h3></div>
      <div class="container-fluid" style="overflow:auto;background-color: black;">
          <div class="scrolling-wrapper row flex-row flex-nowrap gx-2 mt-4 pb-4 pt-2 ">
              {% for movie in moviedetails.object_list %}
              <div class="card card-block col-4 col-9 col-sm-12 col-md-4  col-lg-4 mr-2 border-0"  style="width: 550px; background-color: black;">
                  <a href="{{movie.get_url}}"><img width="10px"  height="250px" src="{{movie.poster.url}}" class="card-img-top" alt="{{movie.title}}"></a>
                  <a href="{{movie.get_url}}">
                      <div class="card-img-overlay">
                      <h5 class="card-title" style="color: white;">{{movie.title}}</h5>
                  </div></a>
              </div>
                   {% endfor %}
          </div>
      </div>
<br>


{% endif %}
<div class="mx-auto">
        {% if moviedetails.paginator.num_pages > 1 %}
        <div class="text-center">
            {% for md in moviedetails.paginator.page_range %}
            <a href="?page={{md}}" class="btn btn-light btn-sm {% if moviedetails.number == pg %} active {% endif %}">{{md}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/ba5a227daf.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</head>
<body>
   <div class="container">
        <div class="row justify-content-center" style="padding-top: 35px;">
            <div class="col-sm-8"></div>
            <div class="col-sm-4">
                <h1 style="text-align: center;">LOGIN</h1>
                <form method="post" style="padding: 15px;">
                    {% csrf_token %}
                    <input type="text" name="username" class="form-control" placeholder="Username">
                    <br> <input type="password" name="password" class="form-control" placeholder="Password">
                    <br><input class="btn" type="submit" name="login" placeholder="Login" style="background-color: rgb(119, 140, 232);color: white;"><br>
                </form>
            </div>
            {% for msg in messages %}
            {{msg}}
            {% endfor %}

        </div>

   </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg " >
    <div class="container-fluid" style="background-color: black;">
      <div class="row" style="background-color: black;">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse col-sm-8" id="navbarNavDropdown">
          {% if user.is_authenticated %}
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active navbtn" aria-current="page" href="{% url 'movieapp:allMoviedetails' %}"><p  class="navbtn" style="color: white;">Home</p></a>
            </li>
            <li class="nav-item">
              <a class="nav-link navbtn" href="{% url 'userapp:logout' %}"><p class="navbtn" style="color: white;" >Logout</p></a>
            </li>
            <li class="nav-item">
              <a class="nav-link navbtn" href="{% url 'userapp:addmovies' %}"><p class="navbtn" style="color: white;" >Add Movie</p></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle navbtn" href="{% url 'movieapp:allMoviedetails' %}" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <p class="navbtn" style="color: white;">Category</p>
              </a>
              <ul style="background-color: black;" class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                {% for cat in links %}
                <li><a class="dropdown-item " href="{{cat.get_url}}"><p style="color: #2272FF;">{{cat.name}}</p></a></li>
                {% endfor %}
              </ul>
            </li>
          </ul>
          {% else %}
          <ul class="navbar-nav">
              <li class="nav-item">
                  <a class="nav-link active navbtn" aria-current="page" href="{% url 'movieapp:allMoviedetails' %}"><p class="navbtn" style="color: white;">Home</p></a>
              </li>
              <li class="nav-item">
                  <a class="nav-link navbtn" href="{% url 'userapp:register' %}"><p class="navbtn" style="color:white;">Register</p></a>
              </li>
              <li class="nav-item">
                <a class="nav-link navbtn" href="{% url 'userapp:login' %}"><p class="navbtn" style="color: white;">Login</p></a>
              </li>
          </ul>

          {% endif %}
        </div>
        <div class="col-sm-4" style=" display: flex;justify-content: center;align-items: center;">
          <form  class="d-flex" action="{% url 'searchapp:searchResult' %}" method="get">
            {% csrf_token %}
            <input style="justify-items: right; width: 250px;height: 45px; background-color:#594d4d ;color: white;border-color: #2272FF;font-color:black;" class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
            <button class="btn btn-outline-success" style="border-color: #2272FF; color: #2272FF;" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
          </form>
        </div>
    </div>
    </div>
 </nav>

templates/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Movie Details</title>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/ba5a227daf.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</head>
<body>
   <div class="container">
        <div class="row justify-content-center" style="padding-top: 35px;">
            <div class="col-sm-8"></div>
            <div class="col-sm-4">
                <h3>Update Movie Details</h3>
                <form method="post"  enctype="multipart/form-data" style="padding: 15px;">
                    {% csrf_token %}
                    {{form.as_p}}
                    <br><input class="btn" type="submit" placeholder="update" style="background-color: rgb(119, 140, 232);color: white;">
                    <a class="btn"  href="{% url 'movieapp:allMoviedetails' %}" type="submit" placeholder="Home" style="background-color: rgb(30, 249, 77);color: white;">Go Home</a><br>
                </form>
            </div>
        </div>
   </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>